version: '3.7'
services:
  automation:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/automation"
    privileged: true
    command: tail -f /dev/null
    environment: 
      - STAYALIVE